# Don't print a new line at the start of the prompt
add_newline = false

# use custom prompt order
format = """
$env_var\
$username\
$directory\
$kubernetes\
$aws\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$package\
$dotnet\
$localip\
$shlvl\
$singularity\
$vcsh\
$fossil_branch\
$fossil_metrics\
$hg_branch\
$pijul_channel\
$docker_context\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""


# Wait 30 milliseconds for starship to check files under the current directory.
scan_timeout = 30

[aws]
format = '[$symbol $profile($region)]($style) '
style = '#668cff'

[aws.region_aliases]
us-east-1 = 'use1'
us-east-2 = 'use2'
us-west-1 = 'usw1'
us-west-2 = 'usw2'

[directory]
truncation_length = 3

[golang]
format = '[$symbol$version]($style)'

[hostname]
ssh_only = true
format = '<[$hostname]($style)>'
trim_at = '.'
disabled = false

[kubernetes]
format = '[$symbol$context\($namespace\)]($style) '
style = 'green'
disabled = false

[python]
format = '[${symbol}${pyenv_prefix}${version}($virtualenv)]($style) '
style = 'yellow'

[ruby]
format = '[$symbol$version]($style) '

[username]
disabled = true
