name: Git Repository Backup

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:        # manual trigger
  schedule:
    - cron: '0 0 * * *'     # runs every day at 00:00 UTC

jobs:
  backup-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create backup directory
        run: mkdir -p ${{ github.workspace }}/repo_backup

      - name: Backup repository
        run: |
          TIMESTAMP=$(date +%F_%H-%M-%S)
          tar -czvf ${{ github.workspace }}/repo_backup/repo_backup_$TIMESTAMP.tar.gz -C ${{ github.workspace }} .

      - name: List backup files
        run: ls -lh ${{ github.workspace }}/repo_backup

      - name: Upload backup as artifact
        uses: actions/upload-artifact@v4  # updated to latest version
        with:
          name: repo-backup-${{ github.run_id }}
          path: ${{ github.workspace }}/repo_backup/repo_backup_*.tar.gz